"""Pin the image tag of a deployment, without touching tracked files.

  python scripts/set_image_tag.py local 3f2a9c1
  python scripts/set_image_tag.py fake  20260101-120000

Writes deploy/k8s/apps/obslab/overlays/_build/kustomization.yaml (git-ignored): an overlay on
top of `local` or `fake` that only sets the image tag of the last build. That is what a CI
"bump" step does, kept out of git here so a local build never dirties the working tree.
Kept in Python (not sed) so it runs the same on Windows, macOS and Linux.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

OVERLAYS = Path(__file__).resolve().parents[1] / "deploy/k8s/apps/obslab/overlays"

TEMPLATE = """# GENERATED by scripts/set_image_tag.py (task app:build). Not tracked by git.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../{base}
images:
  - name: obslab-registry.localhost:5001/obslab      # the name set by overlays/local
    newTag: {tag}
"""


def main() -> int:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    base, tag = sys.argv[1], sys.argv[2]
    if base.startswith("_") or not (OVERLAYS / base / "kustomization.yaml").exists():
        known = sorted(p.name for p in OVERLAYS.iterdir() if not p.name.startswith("_"))
        sys.exit(f"unknown overlay {base!r}: expected one of {known}")
    if not re.fullmatch(r"[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}", tag):
        sys.exit(f"invalid OCI tag: {tag}")
    out = OVERLAYS / "_build" / "kustomization.yaml"
    out.parent.mkdir(exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(TEMPLATE.format(base=base, tag=tag))
    print(f"overlays/_build -> {base} @ {tag}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
